import Foundation

/// Postcode sector -> town lookup table.
/// Generated from postcodes.io BUA (Built-Up Area) data, 2026-03-21.
/// Covers 254 postcode sectors from the practice catchment area.
/// Future: async updater will expand this table at runtime.
extension ExtractionHelpers {

    /// Look up the town/city for a UK postcode using the sector table.
    /// Extracts the sector (outward code + first inward digit) and looks it up.
    /// Returns nil for unknown sectors.
    public static func townForPostcode(_ postcode: String) -> String? {
        guard let m = firstMatch(#"([A-Z]{1,2}\d{1,2}[A-Z]?)\s*(\d)"#, in: postcode.uppercased()) else {
            return nil
        }
        let sector = "\(m[1]) \(m[2])"
        return sectorToTown[sector]
    }

    private static let sectorToTown: [String: String] = [
        "BH12 1": "Poole",
        "BL1 1": "Bolton",
        "BN1 4": "Brighton and Hove",
        "BN1 6": "Brighton and Hove",
        "BN1 8": "Brighton and Hove",
        "BN10 7": "Telscombe Cliffs",
        "BN10 8": "Peacehaven",
        "BN11 3": "Worthing",
        "BN12 6": "Worthing",
        "BN14 0": "Worthing",
        "BN16 1": "Rustington",
        "BN16 3": "Rustington",
        "BN17 6": "Littlehampton",
        "BN2 1": "Brighton and Hove",
        "BN2 5": "Brighton and Hove",
        "BN2 6": "Brighton and Hove",
        "BN20 7": "Eastbourne",
        "BN21 1": "Eastbourne",
        "BN23 5": "Crumbles",
        "BN23 7": "Eastbourne",
        "BN24 5": "Stone Cross",
        "BN26 6": "Wealden",
        "BN27 4": "Lower Dicker",
        "BN3 1": "Brighton and Hove",
        "BN3 2": "Brighton and Hove",
        "BN3 3": "Brighton and Hove",
        "BN3 6": "Brighton and Hove",
        "BN41 2": "Brighton and Hove",
        "BN43 6": "Shoreham-by-Sea",
        "BN44 3": "Upper Beeding",
        "BN5 9": "Small Dole",
        "BN6 8": "Hassocks and Hurstpierpoint",
        "BN7 1": "Lewes",
        "BN7 2": "Lewes",
        "BN7 3": "Plumpton Green",
        "BN8 4": "North Chailey",
        "BR4 9": "Bromley",
        "BR6 8": "Bromley",
        "BS6 6": "Bristol",
        "CM22 7": "Uttlesford",
        "CR0 9": "Croydon",
        "CR2 6": "Croydon",
        "CR2 7": "Croydon",
        "CR3 0": "Caterham",
        "CR3 5": "Caterham",
        "CR3 6": "Caterham",
        "CR3 7": "Woldingham",
        "CR5 1": "Croydon",
        "CR5 2": "Croydon",
        "CR5 3": "Hooley",
        "CR6 9": "Warlingham",
        "CR7 7": "Croydon",
        "CR8 2": "Croydon",
        "CR8 3": "Croydon",
        "CR8 5": "Croydon",
        "CR9 1": "Croydon",
        "CR9 8": "Croydon",
        "CT10 1": "Broadstairs",
        "CT18 8": "Etchinghill",
        "CT19 5": "Folkestone",
        "CV34 5": "Warwick",
        "CV8 2": "Kenilworth",
        "DA13 0": "Vigo Village",
        "DA5 1": "Bexley",
        "DE45 1": "Baslow",
        "E1 1": "Tower Hamlets",
        "E10 7": "Waltham Forest",
        "E14 4": "Tower Hamlets",
        "EC1V 2": "Islington",
        "EC1V 9": "Islington",
        "EC4Y 8": "City and County of the City of London",
        "EX32 0": "North Devon",
        "EX8 2": "Exmouth",
        "GL7 3": "Southrop",
        "GU11 1": "Aldershot",
        "GU15 2": "Camberley",
        "GU2 7": "Guildford",
        "GU29 9": "Easebourne",
        "GU6 7": "Ewhurst",
        "GU7 1": "Godalming",
        "GU9 8": "Farnham",
        "IP31 3": "Mid Suffolk",
        "KT11 1": "Cobham",
        "KT11 2": "Cobham",
        "KT12 2": "Walton-on-Thames",
        "KT12 5": "Hersham",
        "KT13 0": "Byfleet",
        "KT13 8": "Weybridge",
        "KT14 6": "West Byfleet, Sheerwater and New Haw",
        "KT15 2": "Addlestone",
        "KT17 4": "Epsom",
        "KT18 5": "Tadworth and Epsom Downs",
        "KT18 6": "Headley",
        "KT18 7": "Epsom",
        "KT19 8": "Epsom",
        "KT2 7": "Kingston upon Thames",
        "KT20 5": "Tadworth and Epsom Downs",
        "KT20 6": "Lower Kingswood",
        "KT20 7": "Box Hill",
        "KT21 1": "Ashtead",
        "KT21 2": "Ashtead",
        "KT22 0": "Leatherhead",
        "KT22 7": "Leatherhead",
        "KT22 9": "Great Bookham and Fetcham",
        "KT23 3": "Great Bookham and Fetcham",
        "KT23 4": "Great Bookham and Fetcham",
        "KT8 9": "West Molesey",
        "KY11 2": "Fife",
        "LE12 8": "Quorndon",
        "LL19 7": "Prestatyn",
        "NG11 6": "Rushcliffe",
        "NG2 3": "Beeston",
        "NG2 5": "West Bridgford",
        "NW10 7": "Brent",
        "NW8 9": "City of Westminster",
        "OX11 7": "Didcot",
        "OX4 2": "Oxford",
        "PO15 7": "Whiteley",
        "RG1 2": "Reading",
        "RG12 1": "Bracknell",
        "RG14 1": "Newbury",
        "RG4 7": "Caversham",
        "RG6 7": "Reading",
        "RH1 1": "Redhill",
        "RH1 2": "Redhill",
        "RH1 3": "South Merstham",
        "RH1 4": "Redhill",
        "RH1 5": "Redhill",
        "RH1 6": "Redhill",
        "RH10 1": "Crawley",
        "RH10 3": "Crawley",
        "RH10 4": "Crawley Down",
        "RH10 5": "Crawley",
        "RH10 6": "Crawley",
        "RH10 7": "Crawley",
        "RH10 8": "Crawley",
        "RH11 0": "Crawley",
        "RH11 6": "Crawley",
        "RH11 7": "Crawley",
        "RH11 8": "Crawley",
        "RH11 9": "Crawley",
        "RH12 0": "Crawley",
        "RH12 1": "Horsham",
        "RH12 2": "Horsham",
        "RH12 3": "Broadbridge Heath",
        "RH12 4": "Horsham",
        "RH12 5": "Horsham",
        "RH13 0": "Tower Hill",
        "RH13 5": "Horsham",
        "RH13 6": "Horsham",
        "RH13 8": "Horsham",
        "RH13 9": "Southwater",
        "RH14 9": "Billingshurst",
        "RH15 9": "Burgess Hill",
        "RH16 1": "Haywards Heath",
        "RH16 2": "Haywards Heath",
        "RH16 3": "Haywards Heath",
        "RH16 4": "Haywards Heath",
        "RH17 5": "Mid Sussex",
        "RH17 6": "Handcross",
        "RH17 7": "Wivelsfield Green",
        "RH18 5": "Forest Row",
        "RH19 1": "East Grinstead",
        "RH19 2": "Felbridge",
        "RH19 3": "East Grinstead",
        "RH19 4": "East Grinstead",
        "RH2 0": "Reigate",
        "RH2 7": "Reigate",
        "RH2 8": "Nalderswood",
        "RH2 9": "Reigate",
        "RH20 1": "Pulborough",
        "RH20 2": "West Chiltington",
        "RH20 3": "Ashington",
        "RH20 4": "Storrington",
        "RH3 7": "Brockham",
        "RH4 1": "Dorking",
        "RH4 2": "Dorking",
        "RH4 3": "Mole Valley",
        "RH5 4": "Dorking",
        "RH5 5": "Forest Green",
        "RH5 6": "Westhumble",
        "RH6 0": "Hookwood",
        "RH6 7": "Horley",
        "RH6 8": "Horley",
        "RH6 9": "Horley",
        "RH7 6": "Newchapel",
        "RH8 0": "Limpsfield",
        "RH8 9": "Tandridge",
        "RH9 8": "Blindley Heath",
        "S32 3": "Calver",
        "SA99 1": "Swansea",
        "SE1 2": "Southwark",
        "SE1 7": "Lambeth",
        "SE1 9": "Southwark",
        "SE21 8": "Lambeth",
        "SE25 4": "Croydon",
        "SG4 9": "Hitchin",
        "SM1 1": "Sutton",
        "SM1 4": "Sutton",
        "SM2 5": "Sutton",
        "SM2 6": "Sutton",
        "SM3 9": "Sutton",
        "SM4 4": "Merton",
        "SM5 1": "Sutton",
        "SM6 9": "Sutton",
        "SM7 1": "Tadworth and Epsom Downs",
        "SM7 2": "Banstead",
        "SM7 3": "Chipstead and Woodmansterne",
        "SO16 6": "Southampton",
        "SO21 3": "Winchester",
        "SO43 7": "Lyndhurst",
        "SP10 2": "Andover",
        "SW10 9": "Kensington and Chelsea",
        "SW11 5": "Wandsworth",
        "SW11 6": "Wandsworth",
        "SW14 7": "Richmond upon Thames",
        "SW17 0": "Wandsworth",
        "SW19 5": "Merton",
        "SW2 4": "Lambeth",
        "SW3 5": "Kensington and Chelsea",
        "SW9 9": "Lambeth",
        "TA1 2": "Taunton",
        "TN1 1": "Royal Tunbridge Wells",
        "TN11 0": "Tonbridge and Malling",
        "TN12 7": "Tunbridge Wells",
        "TN13 2": "Sevenoaks",
        "TN13 3": "Sevenoaks",
        "TN14 6": "Sevenoaks",
        "TN16 1": "Sevenoaks",
        "TN16 2": "Tatsfield",
        "TN17 2": "Sissinghurst",
        "TN2 4": "Pembury",
        "TN2 5": "Royal Tunbridge Wells",
        "TN20 6": "Mayfield",
        "TN21 8": "Heathfield",
        "TN22 3": "Wealden",
        "TN22 4": "Hadlow Down",
        "TN3 9": "Groombridge",
        "TN34 2": "Hastings",
        "TN39 4": "Bexhill-on-Sea",
        "TN4 8": "Royal Tunbridge Wells",
        "TN5 6": "Wadhurst",
        "TN6 1": "Crowborough",
        "TN6 2": "Crowborough",
        "TN7 4": "Wealden",
        "TN8 5": "Edenbridge",
        "TN8 6": "Sevenoaks",
        "TQ7 1": "Kingsbridge",
        "TW2 5": "Richmond upon Thames",
        "W12 7": "Hammersmith and Fulham",
        "W1G 8": "City of Westminster",
        "WC1V 6": "Camden",
        "WC2A 1": "City of Westminster",
        "WR4 4": "Worcester",
    ]
}
