#ifndef YIANA_TYPST_BRIDGE_H
#define YIANA_TYPST_BRIDGE_H

// Auto-generated by cbindgen. Do not edit.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Compile a Typst template with JSON inputs to PDF.
 *
 * # Safety
 * All pointer parameters must be valid for the given lengths.
 * The caller must free output buffers with `typst_free_buffer`.
 *
 * Returns 0 on success, 1 on error.
 */
int32_t typst_compile_to_pdf(const uint8_t *template_,
                             uintptr_t template_len,
                             const uint8_t *inputs_json,
                             uintptr_t inputs_len,
                             uint8_t **out_pdf,
                             uintptr_t *out_pdf_len,
                             uint8_t **out_error,
                             uintptr_t *out_error_len);

/**
 * Free a buffer allocated by typst_compile_to_pdf.
 *
 * # Safety
 * ptr must have been returned by typst_compile_to_pdf, and len must match.
 */
void typst_free_buffer(uint8_t *ptr, uintptr_t len);

#endif  /* YIANA_TYPST_BRIDGE_H */
